Listen 81
<VirtualHost *:81>
    DocumentRoot /usr/local/apache2/htdocs/html

    <Directory /usr/local/apache2/htdocs/html>
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>